name: CI - Release Branch (Release) - Java Application

on:
  workflow_call:
    inputs:
    
      java-version:
        required: false
        type: string
        default: '21'

      terraform-version:
        required: false
        type: string
        default: '1.9.6'
    
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-java-maven.yml
    with:
      java-version: ${{ inputs.java-version }}

  deploy-artifact:
    name: Prepare & Deploy Final Version
    needs: build
    uses: ./.github/workflows/deploy-java-maven-release.yml
    with:
      java-version: ${{ inputs.java-version }}

  create-docker-image:
    name: Create Docker Image
    needs: [deploy-artifact]
    secrets: inherit
    uses: ./.github/workflows/create-docker-image.yml
    with:
      java-version: ${{ inputs.java-version }}

  apply-terraform:
    uses: ./.github/workflows/apply-terraform-infra.yml
    needs: [create-docker-image]
    secrets: inherit
    with:
      terraform_version: ${{ inputs.terraform-version }}
      base_version: ${{ steps.create-docker-image.outputs.base_version }}
      deploy_infra: true