name: Build mavem project and execute test

on:
  workflow_call:
    inputs:
    
      java-version:
        required: false
        type: string
        default: '21'
      
      aws-region:
        required: false
        type: string
        default: 'us-east-1'
    
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-java-maven.yml
    with:
      java-version: ${{ inputs.java-version }}

  validate-terraform:
    uses: ./.github/workflows/apply-terraform-infra.yml
    needs: [build]
    with:
      terraform_version: '1.9.6'
      deploy_infra: false