name: CI - Release Branch (Release) - Java Application

on:
  workflow_call:
    inputs:
    
      java-version:
        required: false
        type: string
        default: '21'
    
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-java-maven.yml
    with:
      java-version: ${{ inputs.java-version }}

  prepare-release:
    name: Prepare & Deploy Final Version
    needs: build
    uses: ./.github/workflows/deploy-java-maven-release.yml
    with:
      java-version: ${{ inputs.java-version }}

  create-docker-image:
    uses: ./.github/workflows/create-docker-image.yaml
    needs: [build]
    with:
      java-version: ${{ inputs.java-version }}

  apply-terraform:
    uses: ./.github/workflows/apply-terraform-infra.yml
    needs: [create-docker-image]
    with:
      terraform_version: '1.9.6'
      base_version: ${{ steps.create-docker-image.outputs.base_version }}
      deploy_infra: true