name: Build mavem project and execute test

on:
  workflow_call:
    inputs:
    
      java-version:
        required: false
        type: string
        default: '21'
      
      aws-region:
        required: false
        type: string
        default: 'us-east-1'
    
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test
  
  check-infra:
    runs-on: ubuntu-latest
    outputs:
      has-terraform: ${{ steps.check.outputs.has_tf }}
    steps:
      - uses: actions/checkout@v4

      - id: check
        run: |
          if compgen -G "infra/*.tf" > /dev/null; then
            echo "has_tf=true" >> $GITHUB_OUTPUT
          else
            echo "has_tf=false" >> $GITHUB_OUTPUT
          fi

  terraform:
    runs-on: ubuntu-latest
    needs: [build-and-test, check-infra]
    if: needs.check-infra.outputs.has-terraform == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Initialize terraform
        run: cd infra && terraform init

      - name: Validate terraform
        run: cd infra && terraform validate

      - name: Plan terraform
        run: cd infra && terraform plan -var-file="terraform.tfvars" -out=tfplan