name: CI - Snapshot Deploy (Java Library)

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Test
    if: startsWith(github.ref, 'refs/heads/develop/')
    uses: ./.github/workflows/build-java-maven.yml
    with:
      java-version: ${{ inputs.java-version }}

  deploy-snapshot:
    name: Deploy -SNAPSHOT to Nexus
    needs: build
    uses: ./.github/workflows/deploy-java-maven-snapshot.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
