name: Build docker image e deploy

on:
  workflow_call:
    inputs:
    
      java-version:
        required: false
        type: string
        default: '21'
      
      aws-region:
        required: false
        type: string
        default: 'us-east-1'
    
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-java-maven.yml
    with:
      java-version: ${{ inputs.java-version }}
  
  deploy-artifact:
    name: Deploy Artifact to Nexus
    uses: ./.github/workflows/deploy-java-maven.yml
    needs: [build]
    with:
      java-version: ${{ inputs.java-version }}

  create-docker-image:
    runs-on: ubuntu-latest
    needs: [deploy-artifact]
    uses: ./.github/workflows/create-docker-image.yml
    with:
      java-version: ${{ inputs.java-version }}

  apply-terraform:
    uses: ./.github/workflows/apply-terraform-infra.yml
    needs: [create-docker-image]
    with:
      terraform_version: '1.9.6'
      base_version: ${{ steps.create-docker-image.outputs.base_version }}
      deploy_infra: true